### PR TITLE
Switch TestWriteCloudConfig to use a StringIO for output

### PR DESCRIPTION
**Pull request by OddBloke**
As we no longer have to write to a file, we may as well reduce the IO
we're doing during tests.

### CODE REVIEW

**Review by josvazg — COMMENTED** [review]
I suspect lines 282 and 288 in tests.py are to blame of leaving untracked files after running the tests:
'1' & 'output.yaml' with 0 bytes

I guess this is due to the fact that now the first argument is a file, not a filename, so when you test it it creates the file for you. Could it be?

Other than that LGTM!
I really like to use memory instead of files on tests whenever possible.

**Comment by OddBloke** [comment]
@josvazg  Yep, I think you're right; I'll fix those tests in a separate PR.

**Review by josvazg — APPROVED** [review]
LGTM, and I unblock this as Dan will fix the untracked files issue on a separate PR.
I +1 on that as it will confuse this PR otherwise.

**Comment by OddBloke** [comment]
@josvazg I've opened #28.

**Review by philroche — APPROVED** [review]
LGTM

**Pull request merged**
