### PR TITLE
Add snapcraft.yaml that builds a strictly-confined snap

### PR DESCRIPTION
**Pull request by OddBloke**

### CODE REVIEW

**Review by rcj4747 — CHANGES_REQUESTED** [review]
Looks good but after running 'snapcraft snap' we have a few items that should be in .gitignore, they are:
  prime/
  stage/
  ubuntu-standalone-builder_0.1.0_all.snap

Can you add a commit for .gitignore for these files?

**Review by rcj4747 — APPROVED** [review]
And I'll approve this contingent on .gitignore changes.  So if you fix that and get a second review before I'm online again it can be merged.

**Review by josvazg — CHANGES_REQUESTED** [review]
Code LGTM, tox passes and the snap builds.
This is very cool! (just had to run tox & snapcraft, no args)

But I also block the green until .gitignore gets rid of:

	prime/
	stage/
	ubuntu-standalone-builder_0.1.0_all.snap

BTW, tox also produces output.yaml that is left there laying around. Should have said this on an earlier PR, but, could we either git ignore it, or maybe even clean it up as test tear down.

UPDATE:
I discovered another issue. If you run tox AFTER snapcraft, flake8 will blow up. It finds zillions of errors under parts/ 
We should probably skip that folder in flake8 tests. Right?

**Comment by OddBloke** [comment]
@josvazg I've fixed both the .gitignore and the flake8 issue; I'll address the `output.yaml` cruft in a separate PR.

**Review by josvazg — APPROVED** [review]
LGTM!
Happy for now as all it's fixed except output.yaml, which is to be done on a separate PR.

**Pull request merged**
