### PR TITLE
Moved from pushd/popd to using cd instead.

### PR DESCRIPTION
**Pull request by chrisglass**

### CODE REVIEW

**Comment by OddBloke** [comment]
@chrisglass Why this change?

**Comment by chrisglass** [comment]
Well, because it doesn't actually work :)

Turns out pushd fails, and so does popd, but since the "cd" in-between doesn't the overall script still works. We just are left in the launchpad-buildd subdirectory.

**Comment by OddBloke** [comment]
Well, that seems like a pretty good reason. :grin:  Could you amend your commit message to include that motivation?

**Comment by chrisglass** [comment]
Done.

**Review by OddBloke — APPROVED** [review]

**Comment by OddBloke** [comment]
Thanks! Will merge once Travis reports it's happy. :-)

**Pull request merged**
