### PR TITLE
Add en_US aliases for customization commandline options

### PR DESCRIPTION
**Pull request by vorlonofportland**

### CODE REVIEW

**Review by OddBloke — APPROVED** [review]
Approfed.

**Review by josvazg — COMMENTED** [review]
Tox passes tests, but I fail to see the relationship between the commit description about en_US aliases and the use of new flags that are later not used anywhere else.

I think I am missing something here.

**Review by philroche — APPROVED** [review]
LGTM

**Comment by philroche** [comment]
@josvazg The flags are aliases for existing flags but with the same destination. `--binary-customization-script` has the same destination as `--binary-customisation-script` and 
`--customization-script ` has the same destination as `--customisation-script`.

**Comment by OddBloke** [comment]
@josvazg The problem is that @vorlonofportland doesn't write proper English. ;-)

**Comment by vorlonofportland** [comment]
On Thu, Feb 09, 2017 at 09:28:17AM -0800, Daniel Watkins wrote:
> @josvazg The problem is that @vorlonofportland doesn't write proper
> English.  ;-)

American Broadcast Standard!

**Comment by josvazg** [comment]
;-D

**Pull request merged**
